### ISSUE TITLE
Build OpenMVS in Ubuntu16.04 for the last version(04/12/2018)

### ISSUE THREAD

**Issue by XiaoyuBIE1994** [cdcseacave/openMVS#392]
- OpenMVS version: pull from github at 04 Dec. 2018
- System: Ubuntu16.04

Theses days, I try to build OpenMVS in my own computer (Ubuntu 16.04) and I find that the build tutorial is a little old. So, I would like to leave some suggestions if others meet the same problems as me. I use cmake-gui to help me configure the Makefile
- In build tutorial, author uses **main_path=`pwd`**  for vcglib, but the better choice is to use your own installation path for vcglib
- The last version of OpenMVS has some conflicts with openCV4, so it is better to use openCV2 or openCV3 (change the OPENCV_DIR in cmake-gui)
- I use Boost 1.58 at first but the machine gives me a **Error: undefined reference to 'boost::archive.....'** so I choose to [install a Boost 1.63 ](https://askubuntu.com/questions/859333/how-to-install-libboost-version1-59-or-newer-on-ubuntu16-04) and change all my Boost path in cmake
- The default version of cmake for Ubuntu16.04 is 3.5.2 which doesn't support Boost 1.63, so I [install the 
 last version of cmake](https://askubuntu.com/questions/355565/how-do-i-install-the-latest-version-of-cmake-from-the-command-line)

**Comment by cdcseacave** [comment]
I have just tested the build on an empty Ubuntu 16.04 x64 and all work fine for me. I didn't try though using OpenCV 4, can you pls report the problems/fixes?

**Comment by XiaoyuBIE1994** [comment]
when I make with Boost1.58, the error is: 
xb257963@is006704:~/dev/openMVS/build_opt$ make
[ 17%] Built target Common
[ 26%] Built target Math
[ 50%] Built target IO
[ 73%] Built target MVS
[ 75%] Linking CXX executable ../../bin/InterfaceVisualSFM
../../lib/libMVS.a(Scene.cpp.o): In function `boost::archive::text_iarchive& boost::archive::detail::interface_iarchive<boost::archive::text_iarchive>::operator>><boost::archive::class_name_type>(boost::archive::class_name_type&)':
Scene.cpp:(.text._ZN5boost7archive6detail18interface_iarchiveINS0_13text_iarchiveEErsINS0_15class_name_typeEEERS3_RT_[_ZN5boost7archive6detail18interface_iarchiveINS0_13text_iarchiveEErsINS0_15class_name_typeEEERS3_RT_]+0x28): undefined reference to `boost::archive::text_iarchive_impl<boost::archive::text_iarchive>::load_override(boost::archive::class_name_type&)'
../../lib/libMVS.a(Scene.cpp.o): In function `void boost::archive::binary_iarchive_impl<boost::archive::binary_iarchive, char, std::char_traits<char> >::load_override<boost::archive::class_name_type>(boost::archive::class_name_type&)':
Scene.cpp:(.text._ZN5boost7archive20binary_iarchive_implINS0_15binary_iarchiveEcSt11char_traitsIcEE13load_overrideINS0_15class_name_typeEEEvRT_[_ZN5boost7archive20binary_iarchive_implINS0_15binary_iarchiveEcSt11char_traitsIcEE13load_overrideINS0_15class_name_typeEEEvRT_]+0x1d): undefined reference to `boost::archive::basic_binary_iarchive<boost::archive::binary_iarchive>::load_override(boost::archive::class_name_type&)'
collect2: error: ld returned 1 exit status
apps/InterfaceVisualSFM/CMakeFiles/InterfaceVisualSFM.dir/build.make:122: recipe for target 'bin/InterfaceVisualSFM' failed
make[2]: *** [bin/InterfaceVisualSFM] Error 1
CMakeFiles/Makefile2:609: recipe for target 'apps/InterfaceVisualSFM/CMakeFiles/InterfaceVisualSFM.dir/all' failed
make[1]: *** [apps/InterfaceVisualSFM/CMakeFiles/InterfaceVisualSFM.dir/all] Error 2
Makefile:129: recipe for target 'all' failed
make: *** [all] Error 2
