### ISSUE TITLE
Install OpenMVS library fail

### ISSUE THREAD

**Issue by mingchuan123** [cdcseacave/openMVS#147]
Hi, I've finished built openMVS on 16.04 ubuntu, but when I try to use this command "make -j2 && sudo make install". The system reports:

[ 20%] Built target Common
[ 31%] Built target Math
[ 58%] Built target IO
[ 85%] Built target MVS
[ 88%] Linking CXX executable ../../bin/DensifyPointCloud
[ 88%] Linking CXX executable ../../bin/InterfaceVisualSFM
../../lib/libMVS.so: undefined reference to `cuMemFree_v2'
../../lib/libMVS.so: undefined reference to `cuEventCreate'
../../lib/libMVS.so: undefined reference to `cuArray3DCreate_v2'
../../lib/libMVS.so: undefined reference to `cuTexRefSetFilterMode'
../../lib/libMVS.so: undefined reference to `cuLaunchGrid'
../../lib/libMVS.so: undefined reference to `cuSurfRefSetArray'
../../lib/libMVS.so: undefined reference to `cuDeviceGetAttribute'
../../lib/libMVS.so: undefined reference to `cuMemcpyDtoH_v2'
../../lib/libMVS.so: undefined reference to `cuTexRefSetAddressMode'
../../lib/libMVS.so: undefined reference to `cuCtxCreate_v2'
../../lib/libMVS.so: undefined reference to `cuLinkComplete'
../../lib/libMVS.so: undefined reference to `cuStreamWaitEvent'
../../lib/libMVS.so: undefined reference to `cuFuncSetBlockShape'
../../lib/libMVS.so: undefined reference to `cuModuleUnload'
../../lib/libMVS.so: undefined reference to `cuLinkDestroy'
../../lib/libMVS.so: undefined reference to `cuMemsetD32_v2'
../../lib/libMVS.so: undefined reference to `cuParamSetSize'
../../lib/libMVS.so: undefined reference to `cuModuleLoadData'
../../lib/libMVS.so: undefined reference to `cuMemcpy2D_v2'
../../lib/libMVS.so: undefined reference to `cuStreamCreate'
../../lib/libMVS.so: undefined reference to `cuTexRefSetFormat'
../../lib/libMVS.so: undefined reference to `cuLinkCreate_v2'
../../lib/libMVS.so: undefined reference to `cuDeviceGetProperties'
../../lib/libMVS.so: undefined reference to `cuGetErrorName'
../../lib/libMVS.so: undefined reference to `cuDeviceGetCount'
../../lib/libMVS.so: undefined reference to `cuModuleGetTexRef'
../../lib/libMVS.so: undefined reference to `cuTexRefSetFlags'
../../lib/libMVS.so: undefined reference to `cuModuleGetFunction'
../../lib/libMVS.so: undefined reference to `cuLaunchGridAsync'
../../lib/libMVS.so: undefined reference to `cuInit'
../../lib/libMVS.so: undefined reference to `cuGetErrorString'
../../lib/libMVS.so: undefined reference to `cuLinkAddFile_v2'
../../lib/libMVS.so: undefined reference to `cuTexRefSetArray'
../../lib/libMVS.so: undefined reference to `cuParamSetv'
../../lib/libMVS.so: undefined reference to `cuModuleGetSurfRef'
../../lib/libMVS.so: undefined reference to `cuDeviceTotalMem_v2'
../../lib/libMVS.so: undefined reference to `cuDeviceComputeCapability'
../../lib/libMVS.so: undefined reference to `cuCtxDestroy_v2'
../../lib/libMVS.so: undefined reference to `cuLinkAddData_v2'
../../lib/libMVS.so: undefined reference to `cuArrayDestroy'
../../lib/libMVS.so: undefined reference to `cuMemAlloc_v2'
../../lib/libMVS.so: undefined reference to `cuDeviceGetName'
../../lib/libMVS.so: undefined reference to `cuEventDestroy_v2'
../../lib/libMVS.so: undefined reference to `cuStreamDestroy_v2'
../../lib/libMVS.so: undefined reference to `cuMemcpyHtoD_v2'
collect2: error: ld returned 1 exit status
apps/InterfaceVisualSFM/CMakeFiles/InterfaceVisualSFM.dir/build.make:189: recipe for target 'bin/InterfaceVisualSFM' failed
make[2]: *** [bin/InterfaceVisualSFM] Error 1
CMakeFiles/Makefile2:600: recipe for target 'apps/InterfaceVisualSFM/CMakeFiles/InterfaceVisualSFM.dir/all' failed
make[1]: *** [apps/InterfaceVisualSFM/CMakeFiles/InterfaceVisualSFM.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
../../lib/libMVS.so: undefined reference to `cuMemFree_v2'
../../lib/libMVS.so: undefined reference to `cuEventCreate'
../../lib/libMVS.so: undefined reference to `cuArray3DCreate_v2'
../../lib/libMVS.so: undefined reference to `cuTexRefSetFilterMode'
../../lib/libMVS.so: undefined reference to `cuLaunchGrid'
../../lib/libMVS.so: undefined reference to `cuSurfRefSetArray'
../../lib/libMVS.so: undefined reference to `cuDeviceGetAttribute'
../../lib/libMVS.so: undefined reference to `cuMemcpyDtoH_v2'
../../lib/libMVS.so: undefined reference to `cuTexRefSetAddressMode'
../../lib/libMVS.so: undefined reference to `cuCtxCreate_v2'
../../lib/libMVS.so: undefined reference to `cuLinkComplete'
../../lib/libMVS.so: undefined reference to `cuStreamWaitEvent'
../../lib/libMVS.so: undefined reference to `cuFuncSetBlockShape'
../../lib/libMVS.so: undefined reference to `cuModuleUnload'
../../lib/libMVS.so: undefined reference to `cuLinkDestroy'
../../lib/libMVS.so: undefined reference to `cuMemsetD32_v2'
../../lib/libMVS.so: undefined reference to `cuParamSetSize'
../../lib/libMVS.so: undefined reference to `cuModuleLoadData'
../../lib/libMVS.so: undefined reference to `cuMemcpy2D_v2'
../../lib/libMVS.so: undefined reference to `cuStreamCreate'
../../lib/libMVS.so: undefined reference to `cuTexRefSetFormat'
../../lib/libMVS.so: undefined reference to `cuLinkCreate_v2'
../../lib/libMVS.so: undefined reference to `cuDeviceGetProperties'
../../lib/libMVS.so: undefined reference to `cuGetErrorName'
../../lib/libMVS.so: undefined reference to `cuDeviceGetCount'
../../lib/libMVS.so: undefined reference to `cuModuleGetTexRef'
../../lib/libMVS.so: undefined reference to `cuTexRefSetFlags'
../../lib/libMVS.so: undefined reference to `cuModuleGetFunction'
../../lib/libMVS.so: undefined reference to `cuLaunchGridAsync'
../../lib/libMVS.so: undefined reference to `cuInit'
../../lib/libMVS.so: undefined reference to `cuGetErrorString'
../../lib/libMVS.so: undefined reference to `cuLinkAddFile_v2'
../../lib/libMVS.so: undefined reference to `cuTexRefSetArray'
../../lib/libMVS.so: undefined reference to `cuParamSetv'
../../lib/libMVS.so: undefined reference to `cuModuleGetSurfRef'
../../lib/libMVS.so: undefined reference to `cuDeviceTotalMem_v2'
../../lib/libMVS.so: undefined reference to `cuDeviceComputeCapability'
../../lib/libMVS.so: undefined reference to `cuCtxDestroy_v2'
../../lib/libMVS.so: undefined reference to `cuLinkAddData_v2'
../../lib/libMVS.so: undefined reference to `cuArrayDestroy'
../../lib/libMVS.so: undefined reference to `cuMemAlloc_v2'
../../lib/libMVS.so: undefined reference to `cuDeviceGetName'
../../lib/libMVS.so: undefined reference to `cuEventDestroy_v2'
../../lib/libMVS.so: undefined reference to `cuStreamDestroy_v2'
../../lib/libMVS.so: undefined reference to `cuMemcpyHtoD_v2'
collect2: error: ld returned 1 exit status
apps/DensifyPointCloud/CMakeFiles/DensifyPointCloud.dir/build.make:189: recipe for target 'bin/DensifyPointCloud' failed
make[2]: *** [bin/DensifyPointCloud] Error 1
CMakeFiles/Makefile2:658: recipe for target 'apps/DensifyPointCloud/CMakeFiles/DensifyPointCloud.dir/all' failed
make[1]: *** [apps/DensifyPointCloud/CMakeFiles/DensifyPointCloud.dir/all] Error 2
Makefile:127: recipe for target 'all' failed
make: *** [all] Error 2

Can anyone help, i will be appreciated.

**Comment by saedrna** [comment]
OpenMVS use cuda driver api, so normal find_package(CUDA) is not enough to detect the driver lib. try  ```-lcuda``` after libMVS in cmake file.

**Comment by jaspermine** [comment]
@saedrna Thanks! This works in Ubuntu 16.10, was having the same error.

**Comment by alexsmartens** [comment]
@saedrna Thanks, it helped me as well.
