### ISSUE TITLE
Build is broken because of the use of discontinued C++ features

### ISSUE THREAD

**Issue by yurivict** [cdcseacave/openMVS#1075]
**Describe the bug**
```
In file included from /wrkdirs/usr/ports/graphics/openmvs/work/openMVS-2.2.0/libs/MVS/Mesh.cpp:58:
In file included from /usr/local/include/vcglib/vcg/complex/algorithms/isotropic_remeshing.h:27:
In file included from /usr/local/include/vcglib/vcg/complex/algorithms/update/curvature.h:30:
/usr/local/include/vcglib/vcg/complex/algorithms/point_sampling.h:716:10: error: no member named 'random_shuffle' in namespace 'std'
    std::random_shuffle(faceVec.begin(),faceVec.end(), p_myrandom);
    ~~~~~^
/usr/local/include/vcglib/vcg/complex/algorithms/point_sampling.h:726:10: error: no member named 'random_shuffle' in namespace 'std'
    std::random_shuffle(vertVec.begin(),vertVec.end(), p_myrandom);
    ~~~~~^
```

You use C++17, and ```std::random_shuffle``` was removed in C++17.

Version: 2.2.0
clang-16
FreeBSD 13.2

**Comment by cdcseacave** [comment]
What repo do u use of VCG?

**Comment by yurivict** [comment]
https://github.com/cnr-isti-vclab/vcglib version 2020.09

**Comment by cdcseacave** [comment]
Try using the version used in the build documentation, a fork on my account

**Comment by yurivict** [comment]
> Try using the version used in the build documentation, a fork on my account

You should add your version as a git submodule, and build and use it privately then.

I am attempting to fix the FreeBSD port, and it uses the ported version of vcglib.

**Comment by StefanBruens** [comment]
Works fine with the upstream vcglib 2023.12 (the downstream fork is more or less 2022.02).

**Comment by cdcseacave** [comment]
Resolved by using the recommended VCGlib fork (or upstream VCGlib >= 2023.12) which removes deprecated C++17 features.
