### ISSUE TITLE
openMVS  make 

### ISSUE THREAD

**Issue by dxqxiaoqiang** [cdcseacave/openMVS#205]
i do everything as these instructions :https://github.com/cdcseacave/openMVS/wiki/Building. But errors go happen when i make .As following :
[ 88%] Building CXX object apps/Viewer/CMakeFiles/Viewer.dir/Window.cpp.o
In file included from /home/dxq/openMVS-master/apps/Viewer/../../libs/MVS/../Common/Types.h:69:0,
                 from /home/dxq/openMVS-master/apps/Viewer/../../libs/MVS/../Common/Common.h:176,
                 from /home/dxq/openMVS-master/apps/Viewer/../../libs/MVS/Common.h:42,
                 from /home/dxq/openMVS-master/apps/Viewer/Common.h:42,
                 from /home/dxq/openMVS-master/openMVS_build/apps/Viewer/cotire/Viewer_CXX_prefix.cxx:4,
                 from /home/dxq/openMVS-master/openMVS_build/apps/Viewer/cotire/Viewer_CXX_prefix.hxx:4:
/home/dxq/openMVS-master/apps/Viewer/../../libs/MVS/../Common/FastDelegateCPP11.h: In constructor ‘fastdelegate::delegate<R(A ...)>::delegate() [with R = bool; A = {const char*, const char*}]’:
/home/dxq/openMVS-master/apps/Viewer/../../libs/MVS/../Common/FastDelegateCPP11.h:48:5: error: conversion from ‘std::nullptr_t’ to non-scalar type ‘std::shared_ptr<void>’ requested
     delegate(void) = default;
     ^
/home/dxq/openMVS-master/apps/Viewer/Window.cpp: In constructor ‘VIEWER::Window::Window()’:
/home/dxq/openMVS-master/apps/Viewer/Window.cpp:49:33: note: synthesized method ‘fastdelegate::delegate<R(A ...)>::delegate() [with R = bool; A = {const char*, const char*}]’ first required here 
  prevPos(Eigen::Vector2d::Zero())
make[2]: *** [apps/Viewer/CMakeFiles/Viewer.dir/Window.cpp.o] Error 1
make[1]: *** [apps/Viewer/CMakeFiles/Viewer.dir/all] Error 2
make: *** [all] Error 2
I don't know where is  wrong  @cdcseacave
                                 ^

**Comment by cdcseacave** [comment]
Something you are not doing as in the wiki, as that works on a clean Ubuntu 16.04.
The problem seems to be in FastDelegateCPP11.h, which is a 3rd party library, that seems to have problems on your system. Pls contact the developer of that library if the problem persists.

**Comment by RasmusB** [comment]
Hello,
sorry for hijacking this issue, I'm not sure if I have the same issue but I also have trouble compiling. 
I'm on Linux Mint which is based on Ubuntu 16.04. I followed the instructions in the wiki, everything worked apart from having to set DVCG_DIR to the full path, using the main_path variable did not work for me. 

Trying to compile openMVS i get the following error:
`../../lib/libCommon.a(CUDA.cpp.o): In function `SEACAVE::CUDA::KernelRT::Reset()':
CUDA.cpp:(.text._ZN7SEACAVE4CUDA8KernelRT5ResetEv+0x72): undefined reference to `cuMemFree_v2'
CUDA.cpp:(.text._ZN7SEACAVE4CUDA8KernelRT5ResetEv+0x85): undefined reference to `cuGetErrorName'
CUDA.cpp:(.text._ZN7SEACAVE4CUDA8KernelRT5ResetEv+0x92): undefined reference to `cuGetErrorString'
CUDA.cpp:(.text._ZN7SEACAVE4CUDA8KernelRT5ResetEv+0x132): undefined reference to `cuMemFree_v2'
CUDA.cpp:(.text._ZN7SEACAVE4CUDA8KernelRT5ResetEv+0x145): undefined reference to `cuGetErrorName'
CUDA.cpp:(.text._ZN7SEACAVE4CUDA8KernelRT5ResetEv+0x152): undefined reference to `cuGetErrorString'
../../lib/libCommon.a(CUDA.cpp.o): In function `SEACAVE::CUDA::KernelRT::Reset(char const*)':
CUDA.cpp:(.text._ZN7SEACAVE4CUDA8KernelRT5ResetEPKc+0x33): undefined reference to `cuModuleGetFunction'
CUDA.cpp:(.text._ZN7SEACAVE4CUDA8KernelRT5ResetEPKc+0xa0): undefined reference to `cuGetErrorName'
CUDA.cpp:(.text._ZN7SEACAVE4CUDA8KernelRT5ResetEPKc+0xacapps/InterfaceVisualSFM/CMakeFiles/InterfaceVisualSFM.dir/build.make:153: recipe for target 'bin/InterfaceVisualSFM' failed
): undefinedmake[2]: *** [bin/InterfaceVisualSFM] Error 1
 reference to `cuGetErrorString'
CUDA.cpp:(.text._ZN7SEACAVE4CUDA8KernelRT5ResetEPKc+0x112): undefined reference to `cuModuleUnload'
CUDA.cpp:(.text._ZN7SEACAVE4CUDA8KernelRT5ResetEPKc+0x1e8): undefined reference to `cuGetErrorName'
CUDA.cpp:(.text._ZN7SEACAVE4CUDA8KernelRT5ResetEPKc+0x1f5): undefined reference to `cuGetErrorString'
../../lib/libCommon.a(CUDA.cpp.o): In function `SEACAVE::CUDA::KernelRT::Reset(SEACAVE::CSharedPtr<SEACAVE::CUDA::ModuleRT> const&, char const*)':
CUDA.cpp:(.text._ZN7SEACAVE4CUDA8KernelRT5ResetERKNS_10CSharedPtrINS0_8ModuleRTEEEPKc+0x4e): undefined reference to `cuModuleUnload'
CUDA.cpp:(.text._ZN7SEACAVE4CUDA8KernelRT5ResetERKNS_10CSharedPtrINS0_8ModuleRTEEEPKc+0xa3CMakeFiles/Makefile2:604: recipe for target 'apps/InterfaceVisualSFM/CMakeFiles/InterfaceVisualSFM.dir/all' failed
): undefinedmake[1]: *** [apps/InterfaceVisualSFM/CMakeFiles/InterfaceVisualSFM.dir/all] Error 2
 reference to `cuModuleGetFunction'
CUDA.cpp:(.text._ZN7SEACAVE4CUDA8KernelRT5ResetERKNS_10CSharedPtrINS0_8ModuleRTEEEPKc+0x110): undefined reference to `cuGetErrorName'
CUDA.cpp:(.text._ZN7SEACAVE4CUDA8KernelRT5ResetERKNS_10CSharedPtrINS0_8ModuleRTEEEPKc+0x11c): undefined reference to `cuGetErrorString'
CUDA.cpp:(.text._ZN7SEACAVE4CUDA8KernelRT5ResetERKNS_10CSharedPtrINS0_8ModuleRTEEEPKc+0x182): undefined reference to `cuModuleUnload'
CUDA.cpp:(.text._ZN7SEACAVE4CUDA8KernelRT5ResetERKNS_10CSharedPtrINS0_8ModuleRTEEEPKc+0x218): undefined reference to `cuGetErrorName'
CUDA.cpp:(.text._ZN7SEACAVE4CUDA8KernelRT5ResetERKNS_10CSharedPtrINS0_8ModuleRTEEEPKc+0x225): undefined reference to `cuGetErrorString'
CUDA.cpp:(.text._ZN7SEACAVE4CUDA8KernelRT5ResetERKNS_10CSharedPtrINS0_8ModuleRTEEEPKc+0x2c8): undefined reference to `cuGetErrorName'
CUDA.cpp:(.text._ZN7SEACAVE4CUDA8KernelRT5ResetERKNS_10CSharedPtrINS0_8ModuleRTEEEPKc+0x2d5): undefined reference to `cuGetErrorString'
../../lib/libCommon.a(CUDA.cpp.o): In function `SEACAVE::CUDA::KernelRT::Reset(char const*, char const*, int)':
CUDA.cpp:(.text._ZN7SEACAVE4CUDA8KernelRT5ResetEPKcS3_i+0x7a): undefined reference to `cuModuleUnload'
CUDA.cpp:(.text._ZN7SEACAVE4CUDA8KernelRT5ResetEPKcS3_i+0x11c): undefined reference to `cuModuleUnload'
CUDA.cpp:(.text._ZN7SEACAVE4CUDA8KernelRT5ResetEPKcS3_i+0x170): undefined reference to `cuGetErrorName'
CUDA.cpp:(.text._ZN7SEACAVE4CUDA8KernelRT5ResetEPKcS3_i+0x17d): undefined reference to `cuGetErrorString'
CUDA.cpp:(.text._ZN7SEACAVE4CUDA8KernelRT5ResetEPKcS3_i+0x1e0): undefined reference to `cuGetErrorName'
CUDA.cpp:(.text._ZN7SEACAVE4CUDA8KernelRT5ResetEPKcS3_i+0x1ed): undefined reference to `cuGetErrorString'
../../lib/libCommon.a(CUDA.cpp.o): In function `SEACAVE::CUDA::KernelRT::_AddParam(SEACAVE::CUDA::KernelRT::InputParam const&)':
CUDA.cpp:(.text._ZN7SEACAVE4CUDA8KernelRT9_AddParamERKNS1_10InputParamE+0x5f): undefined reference to `cuMemAlloc_v2'
CUDA.cpp:(.text._ZN7SEACAVE4CUDA8KernelRT9_AddParamERKNS1_10InputParamE+0x11c): undefined reference to `cuMemFree_v2'
CUDA.cpp:(.text._ZN7SEACAVE4CUDA8KernelRT9_AddParamERKNS1_10InputParamE+0x150): undefined reference to `cuMemcpyHtoD_v2'
CUDA.cpp:(.text._ZN7SEACAVE4CUDA8KernelRT9_AddParamERKNS1_10InputParamE+0x17f): undefined reference to `cuParamSetv'
CUDA.cpp:(.text._ZN7SEACAVE4CUDA8KernelRT9_AddParamERKNS1_10InputParamE+0x198): undefined reference to `cuGetErrorName'
CUDA.cpp:(.text._ZN7SEACAVE4CUDA8KernelRT9_AddParamERKNS1_10InputParamE+0x1a5): undefined reference to `cuGetErrorString'
../../lib/libCommon.a(CUDA.cpp.o): In function `SEACAVE::CUDA::KernelRT::_AddParam(SEACAVE::CUDA::KernelRT::OutputParam const&)':
CUDA.cpp:(.text._ZN7SEACAVE4CUDA8KernelRT9_AddParamERKNS1_11OutputParamE+0x5c): undefined reference to `cuMemAlloc_v2'
CUDA.cpp:(.text._ZN7SEACAVE4CUDA8KernelRT9_AddParamERKNS1_11OutputParamE+0xbf): undefined reference to `cuParamSetv'
CUDA.cpp:(.text._ZN7SEACAVE4CUDA8KernelRT9_AddParamERKNS1_11OutputParamE+0x144): undefined reference to `cuMemFree_v2'
CUDA.cpp:(.text._ZN7SEACAVE4CUDA8KernelRT9_AddParamERKNS1_11OutputParamE+0x168): undefined reference to `cuGetErrorName'
CUDA.cpp:(.text._ZN7SEACAVE4CUDA8KernelRT9_AddParamERKNS1_11OutputParamE+0x175): undefined reference to `cuGetErrorString'
../../lib/libCommon.a(CUDA.cpp.o): In function `SEACAVE::CUDA::KernelRT::GetResult(unsigned long long, SEACAVE::CUDA::KernelRT::ReturnParam const&) const':
CUDA.cpp:(.text._ZNK7SEACAVE4CUDA8KernelRT9GetResultEyRKNS1_11ReturnParamE+0xb): undefined reference to `cuMemcpyDtoH_v2'
../../lib/libCommon.a(CUDA.cpp.o): In function `SEACAVE::CUDA::KernelRT::GetResult(std::initializer_list<SEACAVE::CUDA::KernelRT::ReturnParam> const&) const':
CUDA.cpp:(.text._ZNK7SEACAVE4CUDA8KernelRT9GetResultERKSt16initializer_listINS1_11ReturnParamEE+0x47): undefined reference to `cuMemcpyDtoH_v2'
collect2: error: ld returned 1 exit status
apps/TextureMesh/CMakeFiles/TextureMesh.dir/build.make:153: recipe for target 'bin/TextureMesh' failed
make[2]: *** [bin/TextureMesh] Error 1
CMakeFiles/Makefile2:836: recipe for target 'apps/TextureMesh/CMakeFiles/TextureMesh.dir/all' failed
make[1]: *** [apps/TextureMesh/CMakeFiles/TextureMesh.dir/all] Error 2
Makefile:127: recipe for target 'all' failed
make: *** [all] Error 2
`
Can you please suggest where to start looking to fix this?

**Comment by zsustc** [comment]
@RasmusB i have alomost the same probelm with u and i have try to reinstall openMVG and openMVS several times accoring to the github instructions, but the openMVS make processing always get a failiure. 
the attachment is my openMVS make error report.
[openmvs_make_error_report.txt](https://github.com/cdcseacave/openMVS/files/988909/openmvs_make_error_report.txt)

**Comment by RasmusB** [comment]
Hello,
I'm not trying to fix this anymore. I found a snap package for openmve that worked out of the box.

**Comment by zsustc** [comment]
@RasmusB i also have tried the openMVE. From my point of view, openMVS can obtain more complete and accurate as possible point-cloud.

**Comment by cdcseacave** [comment]
For some reason the CUDA library is not found during linking. But I suggest to disable CUDA functionality for OpenMVS (cmake flag during configuration), as the full functionality is available on CPU and at similar speed.

**Comment by CanCanZeng** [comment]
@dxqxiaoqiang hi, did you come over the problem? I meet the same error.

**Comment by FavorMylikes** [comment]
Have same issue under ubuntu 18.04
