### ISSUE TITLE
does not compile on Ubuntu 14.04

### ISSUE THREAD

**Issue by sweeneychris** [cdcseacave/openMVS#86]
Hi Dan -- I just downloaded the master branch and tried to build OpenMVS. It mostly builds fine until it is time to build and link everything in the Apps folder. When linking InterfaceVisualSfM I get many errors that indicate to me that CUDA is not being linked properly:

Mesh.cpp:(.text._ZN7SEACAVE4CUDA8KernelRTclIIRNS_5cListINS_7TPoint3IfEERKS5_Li0ELi8192EjEERNS3_INS4_IjEERKSA_Li0ELi8192EjEENS1_11OutputParamEjEEE14cudaError_enumiDpOT_[_ZN7SEACAVE4CUDA8KernelRTclIIRNS_5cListINS_7TPoint3IfEERKS5_Li0ELi8192EjEERNS3_INS4_IjEERKSA_Li0ELi8192EjEENS1_11OutputParamEjEEE14cudaError_enumiDpOT_]+0x208): undefined reference to `cuLaunchGrid'
../../lib/libMVS.a(Mesh.cpp.o): In function `cudaError_enum SEACAVE::CUDA::addKernelParam<unsigned int>(CUfunc_st*&, int&, unsigned int const&)':
Mesh.cpp:(.text._ZN7SEACAVE4CUDA14addKernelParamIjEE14cudaError_enumRP9CUfunc_stRiRKT_[_ZN7SEACAVE4CUDA14addKernelParamIjEE14cudaError_enumRP9CUfunc_stRiRKT_]+0x4a): undefined reference to `cuParamSetv'
../../lib/libCommon.a(CUDA.cpp.o): In function `SEACAVE::CUDA::Device::~Device()':
CUDA.cpp:(.text._ZN7SEACAVE4CUDA6DeviceD2Ev[_ZN7SEACAVE4CUDA6DeviceD5Ev]+0x24): undefined reference to `cuCtxDestroy_v2'

Those are just a few examples. I have checked the base directory's CMakeLists.txt and CUDA (v7.5) is being found correctly. Even if I add a line target_link_libraries(InterfaceVisualSFM ${CUDA_LIBRARIES}) to the InterfaceVisualSFM cmake file it still does not work. Similarly, when I add message("${CUDA_LIBRARIES}") to that file it indeed prints the correct location of the cuda library. 

Any ideas?

**Comment by HKUSTmji** [comment]
How about you add a line in the corresponding cmakelists.txt:
`target_link_libraries(InterfaceVisualSFM cuda)`
which links the libcuda.so

**Comment by sweeneychris** [comment]
I already tried that, as written in my report.

**Comment by cdcseacave** [comment]
I do not have CUDA on my linux machine, so didn't test and can't debug, but one quick thing you can do is disable CUDA support, nothing is lost from the functionality of the pipeline. There is an option in the CMake configuration.

**Comment by sweeneychris** [comment]
Sure, that works. But it would be really nice to have CUDA for speedups :)

I don't really understand why the build fails with CUDA for me right now so I wouldn't know how to fix it but I'm happy to help test any patches that may fix it.

**Comment by tzumby** [comment]
I'm having the same problem compiling in Arch linux. Cmake finds the Cuda sdk but I get the same errors  when building and linking.

**Comment by KevinCain** [comment]
My system is running Ubuntu 16.04, GCC 503 with CUDA 7.5.  Like the others, above, I haven't been able to compile OpenMVS.

As suggested above, I commented out the NVidia Cuda Runtime API define in 'ConfigLocal.h' as follows, but am still seeing CUDA-based errors of the kind described above:
> // #define _USE_CUDA

**Comment by cdcseacave** [comment]
As I said before, there is a flag in the CMake script to disable the cuda functionality (OpenMVS_USE_CUDA) so you do NOT have to touch the code!

**Comment by KevinCain** [comment]
Thanks, I didn't know quite where to look.

I set OpenMVS_USE_CUDA to OFF in in 'CMakeLists.txt', e.g.:
> SET(OpenMVS_USE_CUDA OFF CACHE BOOL "Enable CUDA library") 

I'm still seeing compile and link errors, so if the above is the proper way to turn off CUDA support, my trouble must be elsewhere.

**Comment by cdcseacave** [comment]
I tried to say before, but you don't want to listen: you do not have to change the code!!!!!!!!!!!! The purpose of a flag is to change it dynamically.

**Comment by mad-de** [comment]
try deleting both the openMVS and openMVS_build folder and just run

> git clone https://github.com/cdcseacave/openMVS.git openMVS
> mkdir openMVS_build && cd openMVS_build
> cmake . ../openMVS -DCMAKE_BUILD_TYPE=Release -DVCG_DIR="~/vcglib"

**Comment by KevinCain** [comment]
I'm sorry to leave you so exasperated, cdseacave, I do understand and appreciate your point.  But my edits were not destructive, of course.  When I set the flag in the CMake GUI, rather than in the code, I still have the same compile & link errors...

**Comment by cdcseacave** [comment]
that should not be the case: when you change the code, you simply changed the default value, that has no effect on an already existing project. If you change the flag in the existing project and build again the solution there you should have the desired effect.

**Comment by KevinCain** [comment]
Cdseacave, yes, but to be clear, I was rebuilding after setting the default value.

**Comment by KevinCain** [comment]
Mad-de, your suggestions closely approximate the build instructions I followed from the wiki:  https://github.com/cdcseacave/openMVS/wiki/Building.

Following your explicit steps fails, for me, because of a Ceres/Eigen descrepancy which I resolved previously, here: https://groups.google.com/forum/#!topic/ceres-solver/VbiqrQK3FNo

**Comment by KevinCain** [comment]
As I am dragging this thread away from CUDA, I will post separately, thanks.

**Comment by mad-de** [comment]
@KevinCain that was intended. I suppose your USE_CUDA is still called with "true" due to your previous cmake and I can`t really follow what you changed in your cmake cache and cmakelists.txt.

So the most simple way to get the CUDA problem sorted out would be to just set it up again and add the flag when running cmake. (see above)

**Comment by KevinCain** [comment]
It did just that -- I'm ommitting CUDA as you and Pierre suggested and no
longer see CUDA errors.

**Comment by tzumby** [comment]
Did anyone successfully compile this with Cuda? I would like to get some of the operations running on the GPU if possible.

**Comment by frebbles** [comment]
My success has been with Ubuntu 14.04, without CUDA. Have not had success with Ubuntu 15+, this is mainly because it wont do CUDA either (CUDA requires GCC 4.9, anything 5+ wont work, which Ubuntu ship with 15+).

I have the same issues with CUDA compilation, ie, the linking fails.

My hunch is that the CUDA libraries seem to need "nvcc" to perform the compilation, rather than gcc. Which doesnt seem to get triggered by the CMake directives. I dont have enough experience with CMake to verify or rectify this.

Hope this is helpful.

**Comment by cdcseacave** [comment]
no nvcc is needed as all CUDA code is precompiled

**Comment by mad-de** [comment]
@frebbles openMVS should build alright with Ubuntu 15.04 and 15.10 and currently fails with Ubuntu 16.04.
For Ubuntu 15.10 which I would recommend do:

try deleting both the openMVS and openMVS_build folder and just run

```
    git clone https://github.com/cdcseacave/openMVS.git openMVS
    mkdir openMVS_build && cd openMVS_build
    cmake . ../openMVS -DCMAKE_BUILD_TYPE=Release -DVCG_DIR="~/vcglib" -DOpenMVS_USE_CUDA=OFF
    make && sudo make install
```

**Comment by KevinCain** [comment]
@mad-de, are you suggesting that OpenMVS can't be compiled on Ubuntu 16.04
in any form, or it can't be compiled on 16.04 with CUDA support?
