### ISSUE TITLE
openMVS does not build on Ubuntu 16.04

### ISSUE THREAD

**Issue by nh2** [cdcseacave/openMVS#123]
Just leaving this here for people who search for the problem:

When building (commit 79bacacff692ffd9b8631dcf729f6f8a6c76e8be) on Ubuntu 16.04, you may get compile errors where one of the first ones is

```
/usr/include/eigen3/Eigen/src/Core/Matrix.h:296:31: error: no matching function for call to 'Eigen::Matrix<double, 3, 3, 1, 3, 3>::_init1(const SEACAVE::TRMatrixBase<double>&)'
      Base::template _init1<T>(x);
```

and one of the last ones is

```
/usr/include/eigen3/Eigen/src/Core/PlainObjectBase.h:822:30: error: invalid use of incomplete type ‘struct Eigen::internal::enable_if<false, SEACAVE::TPoint3<float>*>’
In file included from /usr/include/eigen3/Eigen/Core:295:0,
                 from ../libs/MVS/../Common/Types.h:118,
                 from ../libs/MVS/../Common/Common.h:176,
                 from ../libs/MVS/Common.h:42,
                 from ../libs/MVS/SceneTexture.cpp:32:
```

(plus a couple thousand lines more C++ error output).

The problem is that Ubuntu 16.04 ships the unstable version of eigen `libeigen3-dev 3.3~beta1-2`, detected by CMake as `3.2.92`, which doesn't seem to work.

*The solution is to install the stable version of Eigen*, and then tell Ceres and OpenMVS to use it.

Example cmake instructions to configure the dependencies (I provide only the cmake config, you still have to install their depencencies, download them, and run `make install` after successful configuration):

* eigen 3.2.9: `cmake .. -DCMAKE_INSTALL_PREFIX=$HOME/opt/eigen`
* ceres 1.11: `cmake .. -DMINIGLOG=ON -DBUILD_TESTING=OFF -DBUILD_EXAMPLES=OFF -DEIGEN_INCLUDE_DIR=$HOME/opt/eigen/include/eigen3 -DCMAKE_INSTALL_PREFIX=$HOME/opt/ceres`
* `cdcseacave/VCG` commit `b42e3ed7f` (no build, only source checkout at `$HOME/src/VCG`)
* openmvs: `cmake . ../ -DCERES_DIR=$HOME/opt/ceres/share/Ceres/ -DEIGEN_DIR=$HOME/opt/eigen/include/eigen3 -DVCG_DIR="$HOME/src/VCG" -DCUDA_SDK_ROOT_DIR=/usr/local/cuda`

For seeing what system-provided dependencies are needed, I recommend looking at this dockerfile: https://github.com/marchelbling/photogrammetry/blob/master/Dockerfile

**Comment by nh2** [comment]
Actually reopening, to ask @cdcseacave if you'd be up to put a special case warning users about this issue into your CMake config when the problematic unstable CMake version is detected.

**Comment by cdcseacave** [comment]
Thanks for this build tutorial. I'll add the warning on the wiki page.

**Comment by nh2** [comment]
Thanks!
